# Generated by Django 6.0.7 on 2026-07-10 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in-progress', 'In progress'), ('done', 'Done')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='goals.goal')),
            ],
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='goals_goal_user_id_7ad9fc_idx'),
        ),
    ]
