# Generated by Django 6.0.7 on 2026-07-10 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='learningsession',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
