# Generated by Django 6.0.7 on 2026-07-10 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_options_alter_learningsession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('repo', 'Repo'), ('doc', 'Doc')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='goals.goal')),
            ],
            options={
                'indexes': [models.Index(fields=['goal', 'type'], name='goals_resou_goal_id_1ff0ae_idx')],
            },
        ),
    ]
