# Generated by Django 6.0.7 on 2026-07-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at']},
        ),
    ]
